export const notificationData = {
    gsoc: [
      {
        name: "Pratyush Singh",
        description: "The Mifos Initiative",
        time: "",
        icon: "gsoclogo.png",
        color: "#00C9A7",
      },
      {
        name: "Rahul Jagwani",
        description: "Global Alliance for Genomics and Health",
        time: "",
        icon: "gsoclogo.png",
        color: "#FFB800",
      },
      {
        name: "Uttkarsh",
        description: "OWASP",
        time: "",
        icon: "gsoclogo.png",
        color: "#FF3D71",
      },
      {
        name: "Akash Singh",
        description: "Keploy",
        time: "",
        icon: "gsoclogo.png",
        color: "#1E86FF",
      },
      {
        name: "Aditya",
        description: "Mifos Initiative",
        time: "",
        icon: "gsoclogo.png",
        color: "#00C9A7",
      },
    ],
    lfx: [
      {
        name: "Ashutosh Pandey",
        description: "LiFT Scholarship Holder",
        time: "",
        icon: "lfxlogo.png",
        color: "#00C9A7",
      },
      {
        name: "Saalim Quadri",
        description: "Linux Kernel Mentorship Program",
        time: "",
        icon: "lfxlogo.png",
        color: "#1E86FF",
      },
      {
        name: "Aayush Kumar",
        description: "LiFT Scholarship Holder",
        time: "",
        icon: "lfxlogo.png",
        color: "#FFB800",
      },
      {
        name: "Pratik Singh",
        description: "LiFT Scholarship Holder",
        time: "",
        icon: "lfxlogo.png",
        color: "#FF3D71",
      },
      {
        name: "Debayan G",
        description: "LiFT Scholarship Holder",
        time: "",
        icon: "lfxlogo.png",
        color: "#1E86FF",
      },
      {
        name: "Bhuvan M",
        description: "LiFT Scholarship Holder",
        time: "",
        icon: "lfxlogo.png",
        color: "#1E86FF",
      },
      {
        name: "Abhyuday Hari",
        description: "LiFT Scholarship Holder",
        time: "",
        icon: "lfxlogo.png",
        color: "#1E86FF",
      },
      {
        name: "Tanmay R K",
        description: "LiFT Scholarship Holder",
        time: "",
        icon: "lfxlogo.png",
        color: "#1E86FF",
      },
    ],
    icpc: [
      {
        name: "Mohit Agarwal",
        description: "ACM-ICPC Regionalist",
        time: "",
        icon: "icpclogo.png",
        color: "#00C9A7",
      },
      {
        name: "Soumya Pattanayak",
        description: "First team to qualify to ICPC regionals from DSCE",
        time: "",
        icon: "icpclogo.png",
        color: "#FFB800",
      },
      {
        name: "Priyanshu Gupta",
        description: "ACM-ICPC Regionalist",
        time: "",
        icon:"icpclogo.png",
        color: "#FF3D71",
      },
    ],
    sih: [
      {
        name: "Debayan G",
        description: "WINNER OF SIH’23",
        time: "",
        icon: "sihlogo.png",
        color: "#00C9A7",
      },
      {
        name: "Akash Singh",
        description: "Winner of HACKBANGLORE | Placed Top 9 in HACKGLOBAL",
        time: "",
        icon: "hackglobal.png",
        color: "#FFB800",
      },
      {
        name: "Madhur Mehta",
        description: "WINNER OF SIH’23",
        time: "",
        icon: "sihlogo.png",
        color: "#FFB800",
      },
      {
        name: "Ankit Kumar Singh",
        description: "WINNER OF CentuRITon'22",
        time: "",
        icon: "centuriton.png",
        color: "#FFB800",
      }, 
      {
        name: "Palak Khandelwal",
        description: "WINNER OF SIH’23",
        time: "",
        icon: "sihlogo.png",
        color: "#FF3D71",
      },      
      
      {
        name: "Sreeniketh Madugula",
        description: "WINNER OF CentuRITon'22",
        time: "",
        icon: "centuriton.png",
        color: "#FFB800",
      },
      {
        name: "Abhyuday Hari",
        description: "Winner of HACKBANGLORE | Placed Top 9 in HACKGLOBAL",
        time: "",
        icon: "hackglobal.png",
        color: "#FFB800",
      },
      {
        name: "Ritabrata Nag",
        description: "WINNER OF SIH’22",
        time: "",
        icon: "sihlogo.png",
        color: "#FFB800",
      },  
      {
        name: "Abhijeet Kumar",
        description: "WINNER OF CentuRITon'22",
        time: "",
        icon: "centuriton.png",
        color: "#FFB800",
      },  
    ]
  };
  