
  export const achievementJson = [
    {
      id: 1,
      name: "Pratyush Singh",
      username: "@GSOC",
      body: "The Mifos Initiative",
      img: "gsoclogo.png",
    },
    {
      id: 2,
      name: "Ashutosh Pandey",
      username: "@LFX",
      body: "LiFT Scholarship Holder",
      img: "lfxlogo.png",
    },
    {
      id: 3,
      name: "Mohit Agarwal",
      username: "@ICPC",
      body: "ACM-ICPC Regionalist",
      img: "icpclogo.png",
    },
    {
      id: 4,
      name: "Debayan G",
      username: "@SIH",
      body: "Winner OF SIH’23",
      img: "sihlogo.png",
    },
    {
      id: 5,
      name: "Rahul Jagwani",
      username: "@GSOC",
      body: "Global Alliance for Genomics and Health",
      img: "gsoclogo.png",
    },
    {
      id: 6,
      name: "Saalim Quadri",
      username: "@LFX",
      body: "Linux Kernel Mentorship Program",
      img: "lfxlogo.png",
    },
    {
      id: 7,
      name: "Soumya Pattanayak",
      username: "@ICPC",
      body: "First team to qualify to ICPC regionals from DSCE",
      img: "icpclogo.png",
    },
    {
      id: 8,
      name: "Akash Singh",
      username: "@HackGlobal",
      body: "Winner of HackBangalore | Top 9 in HackGlobal",
      img: "hackglobal.png",
    },
    {
      id: 9,
      name: "Uttkarsh",
      username: "@GSOC",
      body: "OWASP Foundation",
      img: "gsoclogo.png",
    },
    {
      name: "Aayush Kumar",
      username: "@LFX",
      body: "LiFT Scholarship Holder",
      img: "lfxlogo.png",
    },
    {
      id: 10,
      name: "Priyanshu Gupta",
      username: "@ICPC",
      body: "ACM-ICPC Regionalist",
      img: "icpclogo.png",
    },
    {
      id: 11,
      name: "Madhur Mehta",
      username: "@SIH",
      body: "Winner OF SIH’23",
      img: "sihlogo.png",
    },
    {
      id: 12,
      name: "Akash Singh",
      username: "@GSOC",
      body: "Keploy: E2E test generation",
      img: "gsoclogo.png",
    },
    {
      id: 13,
      name: "Tanmay R K",
      username: "@LFX",
      body: "LiFT Scholarship Holder",
      img: "lfxlogo.png",
    },
    {
      id: 14,
      name: "Aditya",
      username: "@GSOC",
      body: "The Mifos Initiative",
      img: "gsoclogo.png",
    },
    {
      id: 15,
      name: "Abhyuday Hari",
      username: "@HackGlobal",
      body: "Winner of HackBangalore | Top 9 in HackGlobal",
      img: "hackglobal.png",
    },
   
    {
      id: 16,
      name: "Pratik Singh",
      username: "@LFX",
      body: "LiFT Scholarship Holder",
      img: "lfxlogo.png",
    },
    {
      id: 17,
      name: "Palak Khandelwal",
      username: "@SIH",
      body: "Winner OF SIH’23",
      img: "sihlogo.png",
    },
    {
      id: 18,
      name: "Bhuvan M",
      username: "@LFX",
      body: "LiFT Scholarship Holder",
      img: "lfxlogo.png",
    },
    {
      id: 19,
      name: "Ankit Kumar Singh",
      username: "@Centuriton",
      body: "Winner OF CentuRITon'22",
      img: "centuriton.png",
    },
    {
      id: 20,
      name: "Abhyuday Hari",
      username: "@LFX",
      body: "LiFT Scholarship Holder",
      img: "lfxlogo.png",
    },
    {
      id: 21,
      name: "Sreeniketh Madugula",
      username: "@Centuriton",
      body: "Winner OF CentuRITon'22",
      img: "centuriton.png",
    },    
  ];