name: Keploy Test

on:
  push:
    branches:
      - prod
      - staging
      - feature/**
  pull_request:
    branches:
      - prod
      - staging
      - feature/**

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Install Keploy
      run: |
        curl --silent --location 'https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz' | tar xz -C /tmp
        sudo mv /tmp/keploy /usr/local/bin/keploy
        sudo chmod +x /usr/local/bin/keploy

    - name: Keploy Record (Capture Test Cases)
      run: |
        # Start the app in dev mode and record the test cases
        sudo -E keploy record -c "npm run dev"

    - name: Keploy Test (Replay Recorded Tests)
      run: |
        # Replay the recorded tests using the app in dev mode
        sudo -E keploy test -c "npm run dev" --delay 20 --path ./
    
    env:
      NEXT_PUBLIC_MONGODB_URI: ${{ secrets.NEXT_PUBLIC_MONGODB_URI }}
