name: Keploy Test

on:
  push:
    branches:
      - prod
      - staging
      - feature/**
  pull_request:
    branches:
      - prod
      - staging
      - feature/**

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Keploy Report
      uses: keploy/testgpt@main
      with:
        working-directory: /
        delay: 10
        command: "node src/app.js"
        keploy-path: ./
    
    env:
      NEXT_PUBLIC_MONGODB_URI: ${{ secrets.NEXT_PUBLIC_MONGODB_URI }}

