name: Keploy Test

on:
  push:
    branches:
      - prod
      - staging
      - feature/**
  pull_request:
    branches:
      - prod
      - staging
      - feature/**

jobs:
  keploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test-Report
        uses: keploy/testgpt@main
        with:
            command: "npm run dev" 
          
        env:
            NEXT_PUBLIC_MONGODB_URI: ${{ secrets.NEXT_PUBLIC_MONGODB_URI }}
