name: Keploy Test

on:
  push:
    branches:
      - prod
      - staging
      - feature/**
  pull_request:
    branches:
      - prod
      - staging
      - feature/**

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install

      - name: Install Keploy
        run: |
         curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz --overwrite -C /tmp
         sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin/keploy

      - name: Run Keploy Tests
        run: |          
          keploy test -c "npm run dev" --delay 20
          
        env:
          NEXT_PUBLIC_MONGODB_URI: ${{ secrets.NEXT_PUBLIC_MONGODB_URI }}

